
ALTER TABLE ZIPCODE_INFO
ADD ZIP_CODE VARCHAR(5),
    CITY VARCHAR(25),
    STATE VARCHAR(2);


ALTER TABLE INSTRUCTOR_INFO
ADD INSTRUCTOR_ID INT,
    INSTRUCTOR_FIRST_NAME VARCHAR(25),
    INSTRUCTOR_LAST_NAME VARCHAR(25),
    STREET_ADDRESS VARCHAR(50),
    ZIP_CODE VARCHAR(5);


ALTER TABLE COURSE_INFO
ADD COURSE_NO INT,
    COURSE_NAME VARCHAR(50),
    COURSE_PREREQUISITE INT,
    COST DECIMAL(9,2);


ALTER TABLE STUDENT_INFO
ADD STUDENT_ID INT,
    STUDENT_FIRST_NAME VARCHAR(25),
    STUDENT_LAST_NAME VARCHAR(25),
    STREET_ADDRESS VARCHAR(50),
    ZIP_CODE VARCHAR(5);


ALTER TABLE SECTION_INFO
ADD SECTION_ID INT,
    COURSE_NO INT,
    SECTION_NO INT,
    INSTRUCTOR_ID INT,
    LOCATION VARCHAR(50),
    CAPACITY INT;


ALTER TABLE ENROLLMENT_INFO
ADD STUDENT_ID INT,
    SECTION_ID INT,
    ENROLLMENT_DATE DATE;


ALTER TABLE GRADE_INFO
ADD STUDENT_ID INT,
    SECTION_ID INT,
    GRADE_TYPE_CODE CHAR(2),
    GRADE_CODE_OCCURANCE BIGINT,
    NUMERIC_GRADE INT;
