-- 1) ZIPCODE_INFO Table with Constraints
CREATE TABLE ZIPCODE_INFO (
    ZIP_CODE VARCHAR2(5) PRIMARY KEY CONSTRAINT ZIP_PK,
    CITY VARCHAR2(25) NOT NULL CONSTRAINT ZIP_CITY_NN,
    STATE VARCHAR2(2) NOT NULL CONSTRAINT ZIP_STATE_NN
);

-- 2) INSTRUCTOR_INFO Table with Constraints
CREATE TABLE INSTRUCTOR_INFO (
    INSTRUCTOR_ID NUMBER(8, 0) PRIMARY KEY CONSTRAINT INSTRUCTOR_ID_PK,
    INSTRUCTOR_FIRST_NAME VARCHAR2(25) NOT NULL CONSTRAINT INSTRUCTOR_FN_NN,
    INSTRUCTOR_LAST_NAME VARCHAR2(25) NOT NULL CONSTRAINT INSTRUCTOR_LN_NN,
    STREET_ADDRESS VARCHAR2(50),
    ZIP_CODE VARCHAR2(5),
    CONSTRAINT ZIP_INSTRUCTOR_FK FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE)
);

-- 3) COURSE_INFO Table with Constraints
CREATE TABLE COURSE_INFO (
    COURSE_NO NUMBER(8, 0) PRIMARY KEY CONSTRAINT COURSE_NO_PK,
    COURSE_NAME VARCHAR2(50) NOT NULL CONSTRAINT COURSE_NAME_NN,
    COURSE_PREREQUISITE NUMBER(8, 0),
    COST NUMBER(9, 2) NOT NULL CONSTRAINT COST_NN
);

-- 4) STUDENT_INFO Table with Constraints
CREATE TABLE STUDENT_INFO (
    STUDENT_ID NUMBER(8, 0) PRIMARY KEY CONSTRAINT STUDENT_ID_PK,
    STUDENT_FIRST_NAME VARCHAR2(25) NOT NULL CONSTRAINT STUDENT_FN_NN,
    STUDENT_LAST_NAME VARCHAR2(25) NOT NULL CONSTRAINT STUDENT_LN_NN,
    STREET_ADDRESS VARCHAR2(50),
    ZIP_CODE VARCHAR2(5),
    CONSTRAINT ZIP_STUDENT_FK FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE)
);

-- 5) SECTION_INFO Table with Constraints
CREATE TABLE SECTION_INFO (
    SECTION_ID NUMBER(8, 0) PRIMARY KEY CONSTRAINT SECTION_ID_PK,
    COURSE_NO NUMBER(8, 0),
    SECTION_NO NUMBER(3, 0) NOT NULL CONSTRAINT SECTION_NO_NN,
    INSTRUCTOR_ID NUMBER(8, 0),
    LOCATION VARCHAR2(50),
    CAPACITY NUMBER(3, 0),
    CONSTRAINT COURSE_SECTION_FK FOREIGN KEY (COURSE_NO) REFERENCES COURSE_INFO(COURSE_NO),
    CONSTRAINT INSTRUCTOR_SECTION_FK FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR_INFO(INSTRUCTOR_ID)
);

-- 6) ENROLLMENT_INFO Table with Constraints
CREATE TABLE ENROLLMENT_INFO (
    STUDENT_ID NUMBER(8, 0),
    SECTION_ID NUMBER(8, 0),
    ENROLLMENT_DATE DATE,
    PRIMARY KEY (STUDENT_ID, SECTION_ID) CONSTRAINT ENROLLMENT_STUD_SECT_PK,
    CONSTRAINT ENROLLMENT_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID),
    CONSTRAINT ENROLLMENT_SECTION_ID_FK FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID)
);

-- 7) GRADE_INFO Table with Constraints
CREATE TABLE GRADE_INFO (
    STUDENT_ID NUMBER(8, 0),
    SECTION_ID NUMBER(8, 0),
    GRADE_TYPE_CODE CHAR(2),
    GRADE_CODE_OCCURANCE NUMBER(38, 0),
    NUMERIC_GRADE NUMBER(3, 0) DEFAULT 0 CONSTRAINT NUMERIC_GRADE_NN NOT NULL,
    PRIMARY KEY (STUDENT_ID, SECTION_ID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE) CONSTRAINT GRADE_STUD_SECT_TYPE_CODE_PK,
    CONSTRAINT GRADE_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID),
    CONSTRAINT GRADE_SECTION_ID_FK FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID),
    CONSTRAINT CHK_GRADE_TYPE_CODE CHECK (GRADE_TYPE_CODE IN ('FI', 'HM', 'MT', 'PA', 'PJ', 'QZ'))
);
