DESCRIBE COURSE_INFO;

SELECT ZIP_CODE, CITY, STATE AS "STATE" FROM ZIPCODE_INFO;

SELECT DISTINCT STATE FROM ZIPCODE_INFO;

SELECT STUDENT_ID, STUDENT_FIRST_NAME || ' ' || STUDENT_LAST_NAME AS FULL_NAME FROM STUDENT_INFO;

SELECT ZIP_CODE || ', ' || CITY || ', ' || STATE AS ADDRESS FROM ZIPCODE_INFO;

SELECT COURSE_NAME FROM COURSE_INFO;

SELECT COURSE_NAME, COST FROM COURSE_INFO;

SELECT * FROM COURSE_INFO;

SELECT INSTRUCTOR_LAST_NAME, ZIP_CODE FROM INSTRUCTOR_INFO;

SELECT DISTINCT ZIP_CODE FROM STUDENT_INFO;

SELECT STUDENT_FIRST_NAME, STUDENT_LAST_NAME FROM STUDENT_INFO;

SELECT CITY, STATE, ZIP_CODE FROM ZIPCODE_INFO;

SELECT STUDENT_ID, SECTION_ID, NUMERIC_GRADE
FROM GRADE_INFO
WHERE GRADE_TYPE_CODE = 'FI';

SELECT ZIP_CODE, CITY FROM ZIPCODE_INFO WHERE STATE = 'MI';

SELECT STUDENT_FIRST_NAME || ' ' || STUDENT_LAST_NAME AS FULL_NAME, *
FROM ENROLLMENT_INFO E
JOIN STUDENT_INFO S ON E.STUDENT_ID = S.STUDENT_ID
WHERE EXTRACT(MONTH FROM ENROLLMENT_DATE) = 1 AND EXTRACT(YEAR FROM ENROLLMENT_DATE) = 1999
ORDER BY FULL_NAME ASC;

SELECT SECTION_ID, INSTRUCTOR_ID
FROM SECTION_INFO
WHERE COURSE_NO IN (10,20)
ORDER BY INSTRUCTOR_ID ASC;

SELECT STUDENT_ID, SECTION_ID, NUMERIC_GRADE
FROM GRADE_INFO
ORDER BY SECTION_ID ASC, NUMERIC_GRADE DESC;

SELECT COURSE_NO, COURSE_NAME, COST
FROM COURSE_INFO
WHERE COURSE_NAME LIKE '%Intro%';

SELECT * FROM COURSE_INFO
WHERE SUBSTR(COURSE_NAME, -3, 1) = 'a';

SELECT STUDENT_FIRST_NAME || ' ' || STUDENT_LAST_NAME AS FULL_NAME
FROM STUDENT_INFO
WHERE STUDENT_ID BETWEEN 300 AND 350;

SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST BETWEEN 4000 AND 7000;

SELECT INSTRUCTOR_FIRST_NAME
FROM INSTRUCTOR_INFO
WHERE INSTRUCTOR_LAST_NAME = 'Schumer';

SELECT INSTRUCTOR_FIRST_NAME
FROM INSTRUCTOR_INFO
WHERE INSTRUCTOR_LAST_NAME <> 'Schumer';

SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST > 4000;

SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST BETWEEN 3000 AND 7000;

SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST IN (4000, 4500);

SELECT STUDENT_FIRST_NAME, STREET_ADDRESS
FROM STUDENT_INFO
WHERE STUDENT_LAST_NAME LIKE 'S%';

SELECT STUDENT_FIRST_NAME, STREET_ADDRESS
FROM STUDENT_INFO
WHERE SUBSTR(STUDENT_LAST_NAME, 2, 1) = 'o';

SELECT INSTRUCTOR_FIRST_NAME
FROM INSTRUCTOR_INFO
WHERE INSTRUCTOR_LAST_NAME NOT LIKE 'S%';

SELECT COURSE_NAME, COST
FROM COURSE_INFO
WHERE COST BETWEEN 4000 AND 4500 AND COURSE_NAME LIKE 'I%';

SELECT COURSE_NAME, COST, COURSE_PREREQUISITE
FROM COURSE_INFO
WHERE (COST = 2000 AND COURSE_PREREQUISITE = 20) OR COURSE_PREREQUISITE = 25;

SELECT COURSE_NAME, COST, COURSE_PREREQUISITE
FROM COURSE_INFO
WHERE COST = 2000 OR COURSE_PREREQUISITE IN (20,25);

SELECT * FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL;

SELECT STUDENT_LAST_NAME
FROM STUDENT_INFO
WHERE ZIP_CODE IN ('10048','11102','11209');

SELECT INSTRUCTOR_FIRST_NAME, INSTRUCTOR_LAST_NAME
FROM INSTRUCTOR_INFO
WHERE LOWER(INSTRUCTOR_LAST_NAME) LIKE '%i%' AND ZIP_CODE = '10025';

SELECT COURSE_NAME
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NOT NULL AND COST < 1100;

SELECT DISTINCT COST
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NULL;

SELECT COURSE_NO, COURSE_NAME
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NULL
ORDER BY COURSE_NAME ASC;

SELECT COURSE_NO, COURSE_NAME
FROM COURSE_INFO
WHERE COURSE_PREREQUISITE IS NULL
ORDER BY COURSE_NAME DESC;

SELECT CITY, STATE, ZIP_CODE
FROM ZIPCODE_INFO
WHERE STATE IN ('NY','CT')
ORDER BY ZIP_CODE ASC;

SELECT ZIP_CODE, STUDENT_FIRST_NAME, STUDENT_LAST_NAME
FROM STUDENT_INFO
WHERE STUDENT_LAST_NAME = 'Graham'
ORDER BY ZIP_CODE DESC, STUDENT_FIRST_NAME ASC;

SELECT CITY || ', ' || STATE AS CITY_STATE FROM ZIPCODE_INFO;

SELECT INITCAP(STUDENT_FIRST_NAME) AS FIRST_NAME FROM STUDENT_INFO;

SELECT INSTRUCTOR_FIRST_NAME || ', ' || INSTRUCTOR_LAST_NAME AS FULL_NAME FROM INSTRUCTOR_INFO;

SELECT COST, COST+10 AS ADD_10, COST-20 AS SUB_20, COST*30 AS MULT_30, COST/5 AS DIV_5
FROM COURSE_INFO;

SELECT DISTINCT NUMERIC_GRADE, FLOOR(NUMERIC_GRADE/2) AS HALF_GRADE
FROM GRADE_INFO;

SELECT TO_CHAR(COST, '9,999') AS FORMATTED_COST
FROM COURSE_INFO
WHERE COURSE_NO < 25;

SELECT TO_CHAR(COST, '$9,999.00') AS COST_FORMATTED
FROM COURSE_INFO;

SELECT COURSE_NAME, NVL(COURSE_PREREQUISITE,'Not Applicable') AS PREREQUISITE
FROM COURSE_INFO;

SELECT ZIP_CODE, CITY,
DECODE(STATE,'NY','New York','NJ','New Jersey','Others') AS STATE_NAME
FROM ZIPCODE_INFO;
